FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod ./
# Initialize or download dependencies
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o control-plane ./cmd/control-plane

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/control-plane .
EXPOSE 8080
CMD ["./control-plane"]
