package registry

import (
	"context"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"aacb/internal/auth"
	"aacb/internal/database"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

type Server struct {
	DB          *database.DB
	AuthManager *auth.AuthManager
	Addr        string
}

func NewServer(db *database.DB, am *auth.AuthManager, addr string) *Server {
	return &Server{
		DB:          db,
		AuthManager: am,
		Addr:        addr,
	}
}

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()

	// Public Route
	mux.HandleFunc("POST /v1/bootstrap", s.handleBootstrap)

	// Protected Routes (Zero Trust via JWT Authentication)
	mux.Handle("POST /v1/capabilities", s.withJWTAuth(http.HandlerFunc(s.handleRegisterCapabilities)))
	mux.Handle("GET /v1/discovery", s.withJWTAuth(http.HandlerFunc(s.handleDiscovery)))
	mux.Handle("GET /v1/agents/{id}", s.withJWTAuth(http.HandlerFunc(s.handleGetAgent)))

	// Simple healthcheck
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"status":"ok"}`))
	})

	return s.loggingMiddleware(mux)
}

// loggingMiddleware prints basic logs for each request.
func (s *Server) loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		log.Printf("[HTTP] %s %s %s took %v", r.Method, r.URL.Path, r.RemoteAddr, time.Since(start))
	})
}

// withJWTAuth enforces JWT authentication based on NATS User JWTs issued by the Control Plane.
func (s *Server) withJWTAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		authHeader := r.Header.Get("Authorization")
		if authHeader == "" || !strings.HasPrefix(authHeader, "Bearer ") {
			s.writeJSONError(w, http.StatusUnauthorized, "missing or invalid authorization header")
			return
		}

		token := strings.TrimPrefix(authHeader, "Bearer ")

		// Decode the NATS User JWT Claims
		claims, err := jwt.DecodeUserClaims(token)
		if err != nil {
			s.writeJSONError(w, http.StatusUnauthorized, "invalid jwt format: "+err.Error())
			return
		}

		// Verify the JWT signature matches our Account Public Key (Trust Anchor)
		accountPub, err := s.AuthManager.GetAccountPublicKey()
		if err != nil {
			s.writeJSONError(w, http.StatusInternalServerError, "failed to load account public key")
			return
		}

		vr := &jwt.ValidationResults{}
		claims.Validate(accountPub, vr)
		if vr.IsBlocked() || len(vr.Errors()) > 0 {
			s.writeJSONError(w, http.StatusUnauthorized, "jwt validation failed")
			return
		}

		// Set the authenticated agent ID in the context
		ctx := context.WithValue(r.Context(), "agent_id", claims.Name)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

type BootstrapRequest struct {
	AgentID          string `json:"agent_id"`
	APIKey           string `json:"api_key"`
	NKeyPublicKey    string `json:"nkey_public_key"` // The user public NKey generated by the Agent
	Ed25519PublicKey string `json:"ed25519_public_key"`
}

type BootstrapResponse struct {
	NATSUserJWT       string `json:"nats_user_jwt"`
	NATSAccountPubkey string `json:"nats_account_pubkey"`
}

func (s *Server) handleBootstrap(w http.ResponseWriter, r *http.Request) {
	var req BootstrapRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.writeJSONError(w, http.StatusBadRequest, "invalid json payload")
		return
	}

	if req.AgentID == "" || req.APIKey == "" || req.NKeyPublicKey == "" {
		s.writeJSONError(w, http.StatusBadRequest, "agent_id, api_key, and nkey_public_key are required")
		return
	}

	// Validate NKey format (must start with 'U')
	if !nkeys.IsValidPublicUserKey(req.NKeyPublicKey) {
		s.writeJSONError(w, http.StatusBadRequest, "invalid user nkey public key format")
		return
	}

	ctx := r.Context()

	// Get agent from PostgreSQL
	agent, err := s.DB.GetAgent(ctx, req.AgentID)
	if err != nil {
		if errors.Is(err, database.ErrAgentNotFound) {
			// Check if AUTO_REGISTER_AGENTS is enabled (Dev Mode convenience)
			if os.Getenv("AUTO_REGISTER_AGENTS") == "true" {
				if req.Ed25519PublicKey == "" {
					s.writeJSONError(w, http.StatusBadRequest, "ed25519_public_key is required for auto-registration")
					return
				}
				log.Printf("[DEV-MODE] Auto-registering agent: %s", req.AgentID)
				agent, err = s.DB.CreateAgent(ctx, req.AgentID, req.APIKey, req.Ed25519PublicKey, "active", nil)
				if err != nil {
					s.writeJSONError(w, http.StatusInternalServerError, "auto-registration database error: "+err.Error())
					return
				}
				// Set up default ACLs for development
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "agents.*")
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "groups.*")
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "system.audit")
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "system.events")
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "system.alerts")
				_ = s.DB.AddACLRule(ctx, agent.ID, "publish", "rpc.agent.*")

				_ = s.DB.AddACLRule(ctx, agent.ID, "subscribe", "agents."+req.AgentID)
				_ = s.DB.AddACLRule(ctx, agent.ID, "subscribe", "groups.*")
				_ = s.DB.AddACLRule(ctx, agent.ID, "subscribe", "system.events")
				_ = s.DB.AddACLRule(ctx, agent.ID, "subscribe", "system.alerts")
				_ = s.DB.AddACLRule(ctx, agent.ID, "subscribe", "rpc.agent."+req.AgentID)
			} else {
				s.writeJSONError(w, http.StatusForbidden, "unauthorized agent ID (auto-registration disabled)")
				return
			}
		} else {
			s.writeJSONError(w, http.StatusInternalServerError, "database error: "+err.Error())
			return
		}
	}

	// Validate status
	if agent.Status != "active" {
		s.writeJSONError(w, http.StatusForbidden, "agent is suspended or inactive")
		return
	}

	// Compare bootstrap API key
	if !agent.ValidateAgentAPIKey(req.APIKey) {
		s.writeJSONError(w, http.StatusForbidden, "invalid API key")
		return
	}

	// Query agent's ACL rules from DB to construct the NATS User JWT
	acls, err := s.DB.GetACLRules(ctx, agent.ID)
	if err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "failed to query ACLs: "+err.Error())
		return
	}

	var pubACLs []string
	var subACLs []string

	for _, rule := range acls {
		if rule.ActionType == "publish" {
			pubACLs = append(pubACLs, rule.Subject)
		} else if rule.ActionType == "subscribe" {
			subACLs = append(subACLs, rule.Subject)
		}
	}

	// Generate NATS JWT
	natsToken, err := s.AuthManager.GenerateUserJWT(agent.AgentID, req.NKeyPublicKey, pubACLs, subACLs)
	if err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "failed to generate NATS user token: "+err.Error())
		return
	}

	accountPub, _ := s.AuthManager.GetAccountPublicKey()

	// Log audit event
	auditMeta, _ := json.Marshal(map[string]string{
		"agent_id":        req.AgentID,
		"nkey_public_key": req.NKeyPublicKey,
	})
	_ = s.DB.CreateAuditLog(ctx, "agent_bootstrap", req.AgentID, auditMeta)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(BootstrapResponse{
		NATSUserJWT:       natsToken,
		NATSAccountPubkey: accountPub,
	})
}

type CapabilitiesRequest struct {
	Capabilities []string `json:"capabilities"`
}

func (s *Server) handleRegisterCapabilities(w http.ResponseWriter, r *http.Request) {
	authAgentID := r.Context().Value("agent_id").(string)

	var req CapabilitiesRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.writeJSONError(w, http.StatusBadRequest, "invalid json payload")
		return
	}

	ctx := r.Context()

	// Find the agent UUID
	agent, err := s.DB.GetAgent(ctx, authAgentID)
	if err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "database error: "+err.Error())
		return
	}

	// Update capabilities in transaction
	tx, err := s.DB.Pool.Begin(ctx)
	if err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "failed to begin transaction: "+err.Error())
		return
	}
	defer tx.Rollback(ctx)

	// Clear old capabilities
	if err := s.DB.ClearCapabilities(ctx, agent.ID); err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "failed to clear old capabilities: "+err.Error())
		return
	}

	// Add new capabilities
	for _, cap := range req.Capabilities {
		if err := s.DB.AddCapability(ctx, agent.ID, cap); err != nil {
			s.writeJSONError(w, http.StatusInternalServerError, "failed to add capability: "+err.Error())
			return
		}
	}

	if err := tx.Commit(ctx); err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "failed to commit transaction: "+err.Error())
		return
	}

	// Audit capability registry
	auditMeta, _ := json.Marshal(req.Capabilities)
	_ = s.DB.CreateAuditLog(ctx, "capabilities_registered", authAgentID, auditMeta)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"success"}`))
}

type DiscoveryResult struct {
	AgentID string `json:"agent_id"`
}

func (s *Server) handleDiscovery(w http.ResponseWriter, r *http.Request) {
	authAgentID := r.Context().Value("agent_id").(string)
	capability := r.URL.Query().Get("capability")

	if capability == "" {
		s.writeJSONError(w, http.StatusBadRequest, "query parameter 'capability' is required")
		return
	}

	ctx := r.Context()

	agents, err := s.DB.GetAgentsByCapability(ctx, capability)
	if err != nil {
		s.writeJSONError(w, http.StatusInternalServerError, "database error: "+err.Error())
		return
	}

	var response []DiscoveryResult
	for _, id := range agents {
		response = append(response, DiscoveryResult{AgentID: id})
	}

	// Log audit discovery
	auditMeta, _ := json.Marshal(map[string]string{
		"queried_capability": capability,
		"results_count":      string(rune(len(agents))),
	})
	_ = s.DB.CreateAuditLog(ctx, "discovery_query", authAgentID, auditMeta)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(response)
}

func (s *Server) handleGetAgent(w http.ResponseWriter, r *http.Request) {
	agentID := r.PathValue("id")
	if agentID == "" {
		s.writeJSONError(w, http.StatusBadRequest, "path parameter 'id' is required")
		return
	}

	ctx := r.Context()
	agent, err := s.DB.GetAgent(ctx, agentID)
	if err != nil {
		if errors.Is(err, database.ErrAgentNotFound) {
			s.writeJSONError(w, http.StatusNotFound, "agent not found")
			return
		}
		s.writeJSONError(w, http.StatusInternalServerError, "database error: "+err.Error())
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{
		"agent_id":   agent.AgentID,
		"public_key": agent.PublicKey,
		"status":     agent.Status,
	})
}

func (s *Server) writeJSONError(w http.ResponseWriter, code int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	json.NewEncoder(w).Encode(map[string]string{"error": message})
}
